<?php

namespace AppBundle\Repository;

/**
 * Cart_ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cart_ProductRepository extends \Doctrine\ORM\EntityRepository
{
}
