<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function filteredCategory(){
//        $query = $this->getEntityManager()
//            ->createQuery("SELECT c FROM AppBundle:Category c INNER JOIN c.promotion p
//            WHERE
//                p.promotionable_type = :promotion_type
//                AND CURRENT_TIMESTAMP() > p.start_date
//                AND CURRENT_TIMESTAMP() < p.end_date ");
//
//        try {
//            return $query->getSingleResult();
//        } catch (\Doctrine\ORM\NoResultException $e) {
//            return null;
//        }
    }
}
